#!/bin/sh
# Take an srpm and build it locally. This  is sufficient for most "noarch" builds.
set -eux

SRPM="$1"

if [ "${TEST_OS:-}" = rhel-atomic ]; then
    MACRO_RHEL=7
fi

mkdir -p "`pwd`/output"
mkdir -p "`pwd`/rpmbuild"
rpmbuild --rebuild \
  --define "_sourcedir `pwd`" \
  --define "_specdir `pwd`" \
  --define "_builddir `pwd`/rpmbuild" \
  --define "_srcrpmdir `pwd`" \
  --define "_rpmdir `pwd`/output" \
  --define "_buildrootdir `pwd`/build" \
  ${MACRO_RHEL:+--define "rhel $MACRO_RHEL"} \
  "$SRPM"
find `pwd`/output -name '*.rpm' -printf '%f\n' -exec mv {} . \;
rm -r "`pwd`/rpmbuild"
rm -r "`pwd`/output" "`pwd`/build"
