#!/bin/sh
# image-customize script to install cockpit/ws container and the locally built RPM
set -eux

# don't force https:// (self-signed cert)
mkdir -p /etc/cockpit
printf "[WebService]\\nAllowUnencrypted=true\\n" > /etc/cockpit/cockpit.conf

# Install cockpit and run it once to generate certificate; avoids slow startups during tests
podman container runlabel INSTALL cockpit/ws

# fedora-coreos does not have this checkout
if [ ! -d /var/local-tree ]; then
    checkout=$(rpm-ostree status --booted --jsonpath '$.deployments[0].checksum' | tr -d '[]\n "')
    ostree checkout "$checkout" /var/local-tree
fi

# create a local repository for tests
mkdir -p /var/local-repo
ostree init --repo /var/local-repo --mode archive-z2
branch=$(rpm-ostree status | sed -n '/\(fedora\|ostree\|rhel-edge\):/ { s/^.*://; p; q }')
# OCI repository requires rpmostree.inputhash for content comparison; optimization, not important for tests
ostree commit -s "cockpit-tree" --repo /var/local-repo \
    --add-metadata-string version=cockpit-base.1 \
    --add-metadata-string rpmostree.inputhash=dummy \
    --tree=dir=/var/local-tree  -b $branch
ostree remote add local file:///var/local-repo --no-gpg-verify

# switch to our local repository
if [ "${branch%fedora*}" != "$branch" ] || [ "${branch%rhel*}" != "$branch" ]; then
    # on fedora-coreos we use `rpm-ostree install`, which collides on rebase
    rpm-ostree rebase --uninstall=cockpit-ostree local:$branch
else
    # on rhel4edge, cockpit-ostree is not preinstalled
    rpm-ostree rebase local:$branch
fi

# build an OCI image from our local repository; ouput to a local registry,
# as rpm-ostree does not support a local podman image, and using a registry is the realistic use case
if [ "${branch%fedora*}" != "$branch" ]; then
    podman run -d --name ostree-registry --rm -p 5000:5000 -v ostree-oci:/var/lib/registry localhost/test-registry
    mv /etc/containers/registries.conf /etc/containers/registries.conf.orig
    printf '[registries.insecure]\nregistries = ["localhost:5000"]\n' > /etc/containers/registries.conf
    rpm-ostree compose container-encapsulate \
        --repo=/var/local-repo \
        --label ostree.bootable=true \
        $branch registry:localhost:5000/ostree-oci:cockpit1
    podman stop ostree-registry
fi

# Enable ssh password authentication
sed -i '/PasswordAuthentication no/d' /etc/ssh/sshd_config

rpm-ostree status

if firewall-cmd --state >/dev/null 2>&1; then
    firewall-cmd --add-service=cockpit --permanent
fi
